{% set name = "pyqstrat" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyqstrat-{{ version }}.tar.gz
  sha256: 17032aac373649a9fe7ac2364227c761d658d2d188ea48695425891486790514

build:
  number: 5
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ PYTHON }}                           # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=1.24                           # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - pip
    - cython
    
  host:
    - {{ PYTHON }}
    - pip
    - libzip
    - cython
    - numpy >=1.24
    - pip
    - pybind11

  run:
    - python
    - pandas
    - statsmodels
    - ipython
    - sortedcontainers
    - h5py
    - ipywidgets
    - plotly
    - types-python-dateutil >=0.1
    - libzip
    - types-python-dateutil
    - traitlets
    - pandas_market_calendars
    - pyyaml
    - numpy >=1.24
    - pybind11
    - cython

test:
  imports:
    - pyqstrat
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/abbass2/pyqstrat/
  summary: fast / extensible library for backtesting quantitative strategies
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - abbass2
