{% set name = "pyqstrat" %}
{% set version = "0.3.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyqstrat-{{ version }}.tar.gz
  sha256: 5ea5b195c8092393f26b4b2bf095f6f6a6cab99981df70eae15e8c3d00c7093b

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv;
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pybind11
    - numpy
    - pip
    - libzip

  run:
    - python
    - pandas >=0.22
    - matplotlib-base >=2.2.2
    - scipy >=1.0.0
    - statsmodels >=0.11
    - ipython >=6.5.0
    - pybind11 >=2.2
    - sortedcontainers >=2.0.5
    - h5py >=2.9
    - ipywidgets >=7.5
    - plotly >=4.10
    - types-python-dateutil >=0.1
    - {{ pin_compatible('numpy') }}
    - libzip

test:
  imports:
    - pyqstrat
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/abbass2/pyqstrat/
  summary: fast / extensible library for backtesting quantitative strategies
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - abbass2
