{% set name = "pyqstrat" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyqstrat-{{ version }}.tar.gz
  sha256: 17032aac373649a9fe7ac2364227c761d658d2d188ea48695425891486790514

build:
  number: 5
  skip: true  # [py<310]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - pybind11
    - numpy 1.24
    - pip
    - cython
    
  host:
    - python
    - pip
    - libzip
    - cython
    - numpy 1.24
    - pip
    - pybind11

  run:
    - python
    - pandas
    - statsmodels
    - ipython
    - sortedcontainers
    - h5py
    - ipywidgets
    - plotly
    - types-python-dateutil >=0.1
    - libzip
    - types-python-dateutil
    - traitlets
    - pandas_market_calendars
    - pyyaml
    - numpy 1.24

test:
  imports:
    - pyqstrat
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/abbass2/pyqstrat/
  summary: fast / extensible library for backtesting quantitative strategies
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - abbass2
